name: PumpkinPVPReloaded
version: '${project.version}'
main: me.xginko.pumpkinpvpreloaded.PumpkinPVPReloaded
api-version: '1.13'
authors: [xGinko]
description: ${project.description}
website: ${project.url}
folia-supported: true

commands:
  pumpkinpvp:
    usage: /pumpkinpvp [ reload, version, disable ]
    description: admin commands
    aliases:
      - ppvp

permissions:
  pumpkinpvp.cmd.disable:
    description: Disable the plugin
  pumpkinpvp.cmd.reload:
    description: Reload the plugin configuration
  pumpkinpvp.cmd.version:
    description: Show the plugin version